# Generated by Django 5.0.6 on 2024-10-11 11:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_options_alter_category_title'),
        ('conferences', '0003_alter_conference_capacity_alter_conference_program_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='conference',
            name='the start date must be greater than today or equal',
        ),
        migrations.AlterField(
            model_name='conference',
            name='start_date',
            field=models.DateField(default=datetime.date(2024, 10, 11)),
        ),
        migrations.AddConstraint(
            model_name='conference',
            constraint=models.CheckConstraint(check=models.Q(('start_date__gte', datetime.date(2024, 10, 11))), name='the start date must be greater than today or equal'),
        ),
    ]
